In [3]:
import numpy as np
import cv2
from PIL import Image
import os


In [4]:

print(np.version.version)


1.23.5


In [5]:

def appendImg(url,path,target):
    images=[]
    labels=[]
    for i in range(len(url)):
        image=path+url[i];
        
        img=cv2.imread(image)
        img=img/255
        if img is None:
            print()
        else:
            image=cv2.resize(img,(200,200))
        # image = img.resize((200,200))
        # image = img.resize(200,200)
        
        images.append(image)
        labels.append(target)
    images=np.asarray(images);
    labels=np.asarray(labels);
    
    
    return images,labels


In [6]:
x_train[0]

NameError: name 'x_train' is not defined

In [7]:
turl=os.listdir("C:/Users/rnegi/Desktop/ML complete/ML VS code/tumourDetection/brain_tumor_dataset/yes")
# turl1=os.listdir("C:/Users/rnegi/Desktop/ML complete/ML VS code/tumourDetection/yes/yes")
tpath="C:/Users/rnegi/Desktop/ML complete/ML VS code/tumourDetection/brain_tumor_dataset/yes/"
# tpath1="C:/Users/rnegi/Desktop/ML complete/ML VS code/tumourDetection/yes/yes"
img=tpath+turl[0]
print(img)

len(turl)

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:/Users/rnegi/Desktop/ML complete/ML VS code/tumourDetection/brain_tumor_dataset/yes'

In [8]:
img=tpath+turl[0]
img=cv2.imread(img)
image=cv2.resize(img,(200,200))
image.shape

NameError: name 'tpath' is not defined

In [9]:
Nurl=os.listdir("C:/Users/rnegi/Desktop/ML complete/ML VS code/tumourDetection/brain_tumor_dataset/no")
# Nurl1=os.listdir("C:/Users/rnegi/Desktop/ML complete/ML VS code/tumourDetection/no/no")
Npath="C:/Users/rnegi/Desktop/ML complete/ML VS code/tumourDetection/brain_tumor_dataset/no/"
# Npath1="C:/Users/rnegi/Desktop/ML complete/ML VS code/tumourDetection/no/no"

len(Nurl)


FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:/Users/rnegi/Desktop/ML complete/ML VS code/tumourDetection/brain_tumor_dataset/no'

In [10]:
#images with tumour
tumourimage, ttarget=appendImg(turl,tpath,1)
# tumourimage, ttarget=appendImg(turl1,tpath1,1)
normalimage, ntarget=appendImg(Nurl,Npath,0)

NameError: name 'turl' is not defined

In [11]:
data=np.r_[tumourimage,normalimage]
targets=np.r_[ttarget,ntarget]

NameError: name 'tumourimage' is not defined

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(data,targets,random_state=2,test_size=0.2)

NameError: name 'data' is not defined

In [13]:
y_train.shape
print(x_test.shape)


NameError: name 'y_train' is not defined

In [ ]:
import tensorflow as tf


from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D,Flatten,Dense

*Using Transfer learning for Tumor classification


In [80]:
from keras.applications.vgg16 import VGG16

In [81]:
conv_base = VGG16(
    weights='imagenet',
    include_top = False,
    input_shape=(200,200,3)
)

In [82]:
from tensorflow import keras


In [ ]:
os.listdir('C:/Usersrnegi/Desktop/ML complete/ML VS code/tumourDetection/brain_tumor_dataset')

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:/Usersrnegi/Desktop/ML complete/ML VS code/tumourDetection/brain_tumor_dataset'

In [ ]:
modelseq=Sequential()
modelseq.add(conv_base)
modelseq.add(Flatten())
modelseq.add(Dense(1024, activation='relu'))
modelseq.add( Dense(512,activation='relu'))
modelseq.add(Dense(1,activation='sigmoid'))

In [ ]:
conv_base.trainable= False

In [ ]:
modelseq.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
history = modelseq.fit(x_train,y_train,epochs=1,batch_size=16,validation_data=(x_test,y_test))

155/155 [==============================] - 300s 2s/step - loss: 0.4874 - accuracy: 0.8453 - val_loss: 0.1752 - val_accuracy: 0.9239


In [ ]:
# y_predict=modelseq.predict(x_test[0])
# print(y_predict)
x_test[0].shape
xre=np.reshape(x_test[0],(1,200,200,3))

y_predict=modelseq.predict(x_test)
print(y_predict)
y_pred=np.where(y_predict>0.5,1,0)
y_test


20/20 [==============================] - 63s 3s/step
[[8.56199324e-01]
 [7.84535587e-01]
 [9.35492754e-01]
 [3.74982512e-04]
 [6.91602333e-03]
 [5.94386086e-03]
 [6.37108803e-01]
 [9.76017833e-01]
 [8.91379058e-01]
 [9.28852916e-01]
 [9.71614122e-01]
 [8.29426050e-01]
 [1.83551747e-03]
 [9.94820714e-01]
 [1.63844097e-02]
 [9.86246884e-01]
 [9.31297660e-01]
 [9.61186290e-01]
 [2.24667445e-01]
 [5.17331064e-01]
 [9.37608778e-01]
 [2.59043602e-03]
 [8.84358597e-04]
 [1.48432814e-02]
 [8.63794088e-01]
 [6.88527584e-01]
 [8.80457810e-04]
 [2.01111822e-03]
 [2.97563411e-02]
 [3.11568081e-01]
 [2.06768010e-02]
 [1.54853299e-01]
 [9.69522953e-01]
 [7.07606366e-03]
 [9.82239544e-01]
 [1.87033159e-03]
 [1.24504138e-03]
 [1.20827287e-01]
 [9.83650684e-01]
 [9.90356863e-01]
 [6.34023905e-01]
 [1.09142087e-01]
 [9.66746867e-01]
 [9.97487128e-01]
 [1.78681239e-02]
 [1.93115771e-02]
 [5.20605652e-04]
 [9.17648852e-01]
 [9.94647503e-01]
 [7.19846964e-01]
 [1.20349623e-01]
 [1.94490507e-01]
 [1.0831361

In [ ]:
target=['safe','not safe']

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred,target_names=target))


              precision    recall  f1-score   support

        safe       0.88      0.98      0.93       312
    not safe       0.98      0.86      0.92       306

    accuracy                           0.92       618
   macro avg       0.93      0.92      0.92       618
weighted avg       0.93      0.92      0.92       618



In [2]:
# model= Sequential([Conv2D(32,4,input_shape=(200,200,3), activation='relu'),
#                    MaxPooling2D(),
#                     Conv2D(16,4,input_shape=(200,200,3), activation='relu'),
#                     MaxPooling2D(),
#                     Conv2D(16,3,input_shape=(200,200,3), activation='relu'),
#                     MaxPooling2D(),
#                    Flatten(),
#                    Dense(128, activation='relu'),
#                    Dense(64,activation='relu'),
#                    Dense(1,activation='sigmoid')
               
#                    ])

model= Sequential([Conv2D(32,3,input_shape=(200,200,3), activation='relu'),
                   MaxPooling2D(),
                    Conv2D(16,3,input_shape=(200,200,3), activation='relu'),
                    MaxPooling2D(),
                    Conv2D(16,3,input_shape=(200,200,3), activation='relu'),
                    MaxPooling2D(),
                   Flatten(),
                   Dense(1024, activation='relu'),
                   Dense(512,activation='relu'),
                   Dense(1,activation='sigmoid')
               
     
     
     #Conv2D(32,3,input_shape=(200,200,3), activation='relu'),
#                    MaxPooling2D(),
#                     Conv2D(16,3,input_shape=(200,200,3), activation='relu'),
#                     MaxPooling2D(),
#                     Conv2D(16,3,input_shape=(200,200,3), activation='relu'),
#                     MaxPooling2D(),
#                    Flatten(),
#                    Dense(128, activation='relu'),
#                    Dense(64,activation='relu'),
#                    Dense(1,activation='softmax')

               
                   ])


NameError: name 'Sequential' is not defined

In [84]:
model.compile(optimizer='adam',loss=tf.keras.losses.BinaryCrossentropy(),metrics=['accuracy'])

In [85]:
model.fit(x_train,y_train,batch_size=16,epochs=4,validation_data=(x_test,y_test))

Epoch 1/4
155/155 [==============================] - 56s 334ms/step - loss: 0.4317 - accuracy: 0.8048 - val_loss: 0.2320 - val_accuracy: 0.9045
Epoch 2/4
155/155 [==============================] - 52s 333ms/step - loss: 0.1851 - accuracy: 0.9291 - val_loss: 0.0970 - val_accuracy: 0.9725
Epoch 3/4
155/155 [==============================] - 51s 326ms/step - loss: 0.0759 - accuracy: 0.9725 - val_loss: 0.0758 - val_accuracy: 0.9644
Epoch 4/4
155/155 [==============================] - 50s 324ms/step - loss: 0.0292 - accuracy: 0.9899 - val_loss: 0.3559 - val_accuracy: 0.8997


In [87]:
model.save("tumour.h5")

In [ ]:
from keras.models import load_model

In [ ]:
keras_model=load_model('tumour.h5')

In [90]:
#Model metrics

y_predict=model.predict(x_test)
print(y_predict)
y_pred=np.where(y_predict>0.5,1,0)
y_test


20/20 [==============================] - 3s 120ms/step
[[1.00000000e+00]
 [9.99999821e-01]
 [9.99996305e-01]
 [1.60215393e-06]
 [1.83533892e-01]
 [3.00958618e-08]
 [9.99999881e-01]
 [1.00000000e+00]
 [9.99807358e-01]
 [1.21350206e-01]
 [9.99994755e-01]
 [9.99198735e-01]
 [9.74790096e-01]
 [9.99999940e-01]
 [2.68576166e-08]
 [9.99995470e-01]
 [9.99995172e-01]
 [4.84457389e-02]
 [9.98477161e-01]
 [9.99914944e-01]
 [9.99997973e-01]
 [3.93109940e-06]
 [9.83712733e-01]
 [5.33762157e-01]
 [1.00000000e+00]
 [3.32964701e-03]
 [2.14658612e-05]
 [5.08586818e-05]
 [3.18714930e-03]
 [6.87765307e-04]
 [9.63919272e-04]
 [9.99999642e-01]
 [1.00000000e+00]
 [9.39389211e-05]
 [9.99999762e-01]
 [3.84331477e-04]
 [7.62718124e-03]
 [9.93336737e-01]
 [9.92301285e-01]
 [9.99999583e-01]
 [9.53654060e-04]
 [5.80270290e-01]
 [9.99346256e-01]
 [9.99999106e-01]
 [8.74311328e-01]
 [9.14105203e-06]
 [2.02549193e-11]
 [9.99998331e-01]
 [9.99993026e-01]
 [9.99787688e-01]
 [6.09165020e-02]
 [9.99999940e-01]
 [6.64288

array([1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,

In [91]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      0.82      0.90       333
           1       0.82      1.00      0.90       285

    accuracy                           0.90       618
   macro avg       0.91      0.91      0.90       618
weighted avg       0.92      0.90      0.90       618



In [ ]:
#Making a predictive system
input_image="C:/Users/rnegi/Desktop/ML complete/ML VS code/tumourDetection/yes/Y8.jpg"
img=cv2.imread(input_image)
img=cv2.resize(img,(200,200))
imgre=np.reshape(img,[1,200,200,3])
prediction=keras_model.predict(imgre)
print(prediction)

[[0.8051845]]


In [ ]:
print(np.version.version)

1.24.2


In [ ]:
import pandas as pd




In [ ]:


print('hello')






hello


In [ ]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [88]:
from sklearn.metrics import classification_report
y_true = [0, 1, 2, 2, 2]
y_pred = [0, 0, 2, 2, 1]
target_names = ['class 0', 'class 1', 'class 2']
print(classification_report(y_true, y_pred, target_names=target_names))

              precision    recall  f1-score   support

     class 0       0.50      1.00      0.67         1
     class 1       0.00      0.00      0.00         1
     class 2       1.00      0.67      0.80         3

    accuracy                           0.60         5
   macro avg       0.50      0.56      0.49         5
weighted avg       0.70      0.60      0.61         5



In [1]:
model.summary()


NameError: name 'model' is not defined